remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
github:
  # 覆盖默认存储库链接
  repository_url: "https://your-custom-github-url.com" 
  
  # 覆盖下载按钮链接（可选）
  zip_url: "https://custom-download.com/your-project.zip"
  tar_url: "https://custom-download.com/your-project.tar.gz"
